// Generated by CoffeeScript 1.7.1
(function() {
  var Add, checkmark, form, input, niz, x;

  checkmark = document.createElement("span");

  checkmark.innerHTML = "✓";

  checkmark.className = "check";

  x = document.createElement("span");

  x.innerHTML = "✗";

  x.className = "uncheck";

  input = document.querySelector("#text1");

  form = document.querySelector(".form");

  niz = [];

  Add = (function() {
    var add;

    function Add() {
      this.input = document.querySelector("#text1");
      this.ul = document.querySelector(".add");
    }

    Add.prototype = {
      constructor: add,
      appendToDom: function() {
        var i, key, values;
        i = 0;
        while (i < localStorage.length) {
          key = localStorage.key(i);
          values = localStorage.getItem(key);
          $('.add').append($('<li>').text(values.substr(2)).append($("<span>").attr("class", "check").text("✓")).append($('<span>').attr('class', "uncheck").text("✗")));
          i++;
        }
        return add.hmmmm();
      },
      createLocalStorage: function() {
        return $(".uncheck").on("click", function(e) {
          var i, key, values, _results;
          i = 0;
          _results = [];
          while (i < localStorage.length) {
            key = localStorage.key(i);
            values = localStorage.getItem(key);
            if (values === $(this).parents().text()) {
              localStorage.removeItem("note" + key.slice(4, 6));
            }
            _results.push(i++);
          }
          return _results;
        });
      },
      hmmmm: function() {
        $(".uncheck").click(function() {
          var i, key, values, _results;
          $(this).parent().remove();
          i = 0;
          _results = [];
          while (i < localStorage.length) {
            key = localStorage.key(i);
            values = localStorage.getItem(key);
            console.log(values.slice(2));
            console.log($(this).parents().text().replace("✓", "").replace("✗", ""));
            if (values.slice(2) === $(this).parents().text().replace("✓", "").replace("✗", "")) {
              localStorage.removeItem("note" + key.slice(4, 6));
            }
            _results.push(i++);
          }
          return _results;
        });
        return $("li").find(".check").on("click", function(e) {
          $(this).css("color", "green");
          e.target.parentNode.style.textDecoration = "line-through";
          return $(this).next().css("color", "red");
        });
      },
      createView: function() {
        var note, r, t, ul;
        t = this;
        ul = t.ul;
        note = document.createElement("li");
        r = document.createTextNode(add.input.value);
        checkmark = document.createElement("span");
        checkmark.innerHTML = "✓";
        checkmark.className = "check";
        x = document.createElement("span");
        x.innerHTML = "✗";
        x.className = "uncheck";
        localStorage.setItem("note" + localStorage.length, $(checkmark).text() + $(x).text() + add.input.value);
        ul.appendChild(note);
        note.appendChild(checkmark);
        note.appendChild(x);
        note.appendChild(r);
        add.hmmmm();
        return add.createLocalStorage();
      },
      onEnter: function(e) {
        if (e.keyCode === 13 && add.input.value !== "") {
          e.preventDefault();
          add.createView();
          if (add.input.value !== null) {
            add.input.value = null;
          }
        }
      }
    };

    add = new Add();

    add.createLocalStorage();

    add.input.addEventListener("keypress", add.onEnter, false);

    window.onload = add.appendToDom();

    return Add;

  })();

}).call(this);
